remote_theme: jekyll/cayman
title: Daniele Parimbelli
subtitle: prova
author:
  name: 
  email: daniele.parimbelli3@gmail.com
  
description: 
linkedin_username: linkedin

minima:
  social_links:
    linkedin: linkedin
