theme: minima
title: Daniele Parimbelli

author: Data Scientist
email: 
description: daniele.parimbelli3@gmail.com
linkedin_username: daniele-parimbelli

minima:
  social_links:
    linkedin: linkedin
  
