remote_theme: jekyll/minima
title: Daniele Parimbelli

author: Data Scientist
email: daniele.parimbelli3@gmail.com
description:
linkedin_username: linkedin

minima:
  social_links:
    linkedin: linkedin
  
