remote_theme: jekyll/minima
title: Home
author:
  name: Daniele Parimbelli
  email: daniele.parimbelli3@gmail.com
  
description: description
linkedin_username: linkedin

minima:
  social_links:
    linkedin: linkedin
