remote_theme: jekyll/minima
title: Daniele Parimbelli
subtitle: prova
author:
  name: 
  email:
  
description: daniele.parimbelli3@gmail.com
linkedin_username: linkedin

minima:
  social_links:
    linkedin: linkedin
