remote_theme: jekyll/minima
title: Daniele Parimbelli
author:
  name: Daniele Parimbelli
  email: daniele.parimbelli3@gmail.com
  
description:
linkedin_username: linkedin

minima:
  social_links:
    linkedin: linkedin
